//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  seo_collection: Seo_Collection;
  seo_collectionConnection: Seo_CollectionConnection;
  influencer: Influencer;
  influencerConnection: InfluencerConnection;
  resource: Resource;
  resourceConnection: ResourceConnection;
  feature: Feature;
  featureConnection: FeatureConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySeo_CollectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySeo_CollectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Seo_CollectionFilter>;
};


export type QueryInfluencerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryInfluencerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<InfluencerFilter>;
};


export type QueryResourceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResourceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourceFilter>;
};


export type QueryFeatureArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFeatureConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeatureFilter>;
};

export type DocumentFilter = {
  seo_collection?: InputMaybe<Seo_CollectionFilter>;
  influencer?: InputMaybe<InfluencerFilter>;
  resource?: InputMaybe<ResourceFilter>;
  feature?: InputMaybe<FeatureFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Seo_Collection | Influencer | Resource | Feature | Folder;

export type Seo_Collection = Node & Document & {
  __typename?: 'Seo_collection';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  relatedRestaurantSlugs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  relatedInfluencerSlugs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  relatedCollectionSlugs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Seo_CollectionFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  tags?: InputMaybe<StringFilter>;
  relatedRestaurantSlugs?: InputMaybe<StringFilter>;
  relatedInfluencerSlugs?: InputMaybe<StringFilter>;
  relatedCollectionSlugs?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Seo_CollectionConnectionEdges = {
  __typename?: 'Seo_collectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Seo_Collection>;
};

export type Seo_CollectionConnection = Connection & {
  __typename?: 'Seo_collectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Seo_CollectionConnectionEdges>>>;
};

export type Influencer = Node & Document & {
  __typename?: 'Influencer';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  country: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  relatedRestaurantSlugs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  relatedCollectionSlugs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type InfluencerFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  relatedRestaurantSlugs?: InputMaybe<StringFilter>;
  relatedCollectionSlugs?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type InfluencerConnectionEdges = {
  __typename?: 'InfluencerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Influencer>;
};

export type InfluencerConnection = Connection & {
  __typename?: 'InfluencerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<InfluencerConnectionEdges>>>;
};

export type Resource = Node & Document & {
  __typename?: 'Resource';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ResourceFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  tags?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ResourceConnectionEdges = {
  __typename?: 'ResourceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Resource>;
};

export type ResourceConnection = Connection & {
  __typename?: 'ResourceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResourceConnectionEdges>>>;
};

export type Feature = Node & Document & {
  __typename?: 'Feature';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FeatureFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type FeatureConnectionEdges = {
  __typename?: 'FeatureConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Feature>;
};

export type FeatureConnection = Connection & {
  __typename?: 'FeatureConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FeatureConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSeo_collection: Seo_Collection;
  createSeo_collection: Seo_Collection;
  updateInfluencer: Influencer;
  createInfluencer: Influencer;
  updateResource: Resource;
  createResource: Resource;
  updateFeature: Feature;
  createFeature: Feature;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSeo_CollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: Seo_CollectionMutation;
};


export type MutationCreateSeo_CollectionArgs = {
  relativePath: Scalars['String']['input'];
  params: Seo_CollectionMutation;
};


export type MutationUpdateInfluencerArgs = {
  relativePath: Scalars['String']['input'];
  params: InfluencerMutation;
};


export type MutationCreateInfluencerArgs = {
  relativePath: Scalars['String']['input'];
  params: InfluencerMutation;
};


export type MutationUpdateResourceArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourceMutation;
};


export type MutationCreateResourceArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourceMutation;
};


export type MutationUpdateFeatureArgs = {
  relativePath: Scalars['String']['input'];
  params: FeatureMutation;
};


export type MutationCreateFeatureArgs = {
  relativePath: Scalars['String']['input'];
  params: FeatureMutation;
};

export type DocumentUpdateMutation = {
  seo_collection?: InputMaybe<Seo_CollectionMutation>;
  influencer?: InputMaybe<InfluencerMutation>;
  resource?: InputMaybe<ResourceMutation>;
  feature?: InputMaybe<FeatureMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  seo_collection?: InputMaybe<Seo_CollectionMutation>;
  influencer?: InputMaybe<InfluencerMutation>;
  resource?: InputMaybe<ResourceMutation>;
  feature?: InputMaybe<FeatureMutation>;
};

export type Seo_CollectionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  relatedRestaurantSlugs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  relatedInfluencerSlugs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  relatedCollectionSlugs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type InfluencerMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  relatedRestaurantSlugs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  relatedCollectionSlugs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ResourceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FeatureMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Seo_CollectionPartsFragment = { __typename: 'Seo_collection', title: string, description: string, date?: string | null, tags?: Array<string | null> | null, relatedRestaurantSlugs?: Array<string | null> | null, relatedInfluencerSlugs?: Array<string | null> | null, relatedCollectionSlugs?: Array<string | null> | null, draft?: boolean | null, body?: any | null };

export type InfluencerPartsFragment = { __typename: 'Influencer', title: string, description: string, country: string, tags?: Array<string | null> | null, relatedRestaurantSlugs?: Array<string | null> | null, relatedCollectionSlugs?: Array<string | null> | null, draft?: boolean | null, body?: any | null };

export type ResourcePartsFragment = { __typename: 'Resource', title: string, description: string, date?: string | null, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null };

export type FeaturePartsFragment = { __typename: 'Feature', title: string, description: string, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null };

export type Seo_CollectionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Seo_CollectionQuery = { __typename?: 'Query', seo_collection: { __typename: 'Seo_collection', id: string, title: string, description: string, date?: string | null, tags?: Array<string | null> | null, relatedRestaurantSlugs?: Array<string | null> | null, relatedInfluencerSlugs?: Array<string | null> | null, relatedCollectionSlugs?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Seo_CollectionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Seo_CollectionFilter>;
}>;


export type Seo_CollectionConnectionQuery = { __typename?: 'Query', seo_collectionConnection: { __typename?: 'Seo_collectionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Seo_collectionConnectionEdges', cursor: string, node?: { __typename: 'Seo_collection', id: string, title: string, description: string, date?: string | null, tags?: Array<string | null> | null, relatedRestaurantSlugs?: Array<string | null> | null, relatedInfluencerSlugs?: Array<string | null> | null, relatedCollectionSlugs?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type InfluencerQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type InfluencerQuery = { __typename?: 'Query', influencer: { __typename: 'Influencer', id: string, title: string, description: string, country: string, tags?: Array<string | null> | null, relatedRestaurantSlugs?: Array<string | null> | null, relatedCollectionSlugs?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type InfluencerConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<InfluencerFilter>;
}>;


export type InfluencerConnectionQuery = { __typename?: 'Query', influencerConnection: { __typename?: 'InfluencerConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'InfluencerConnectionEdges', cursor: string, node?: { __typename: 'Influencer', id: string, title: string, description: string, country: string, tags?: Array<string | null> | null, relatedRestaurantSlugs?: Array<string | null> | null, relatedCollectionSlugs?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ResourceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResourceQuery = { __typename?: 'Query', resource: { __typename: 'Resource', id: string, title: string, description: string, date?: string | null, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ResourceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourceFilter>;
}>;


export type ResourceConnectionQuery = { __typename?: 'Query', resourceConnection: { __typename?: 'ResourceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResourceConnectionEdges', cursor: string, node?: { __typename: 'Resource', id: string, title: string, description: string, date?: string | null, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FeatureQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FeatureQuery = { __typename?: 'Query', feature: { __typename: 'Feature', id: string, title: string, description: string, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FeatureConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeatureFilter>;
}>;


export type FeatureConnectionQuery = { __typename?: 'Query', featureConnection: { __typename?: 'FeatureConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FeatureConnectionEdges', cursor: string, node?: { __typename: 'Feature', id: string, title: string, description: string, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const Seo_CollectionPartsFragmentDoc = gql`
    fragment Seo_collectionParts on Seo_collection {
  __typename
  title
  description
  date
  tags
  relatedRestaurantSlugs
  relatedInfluencerSlugs
  relatedCollectionSlugs
  draft
  body
}
    `;
export const InfluencerPartsFragmentDoc = gql`
    fragment InfluencerParts on Influencer {
  __typename
  title
  description
  country
  tags
  relatedRestaurantSlugs
  relatedCollectionSlugs
  draft
  body
}
    `;
export const ResourcePartsFragmentDoc = gql`
    fragment ResourceParts on Resource {
  __typename
  title
  description
  date
  tags
  draft
  body
}
    `;
export const FeaturePartsFragmentDoc = gql`
    fragment FeatureParts on Feature {
  __typename
  title
  description
  tags
  draft
  body
}
    `;
export const Seo_CollectionDocument = gql`
    query seo_collection($relativePath: String!) {
  seo_collection(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Seo_collectionParts
  }
}
    ${Seo_CollectionPartsFragmentDoc}`;
export const Seo_CollectionConnectionDocument = gql`
    query seo_collectionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Seo_collectionFilter) {
  seo_collectionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Seo_collectionParts
      }
    }
  }
}
    ${Seo_CollectionPartsFragmentDoc}`;
export const InfluencerDocument = gql`
    query influencer($relativePath: String!) {
  influencer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...InfluencerParts
  }
}
    ${InfluencerPartsFragmentDoc}`;
export const InfluencerConnectionDocument = gql`
    query influencerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: InfluencerFilter) {
  influencerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...InfluencerParts
      }
    }
  }
}
    ${InfluencerPartsFragmentDoc}`;
export const ResourceDocument = gql`
    query resource($relativePath: String!) {
  resource(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResourceParts
  }
}
    ${ResourcePartsFragmentDoc}`;
export const ResourceConnectionDocument = gql`
    query resourceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResourceFilter) {
  resourceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResourceParts
      }
    }
  }
}
    ${ResourcePartsFragmentDoc}`;
export const FeatureDocument = gql`
    query feature($relativePath: String!) {
  feature(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FeatureParts
  }
}
    ${FeaturePartsFragmentDoc}`;
export const FeatureConnectionDocument = gql`
    query featureConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FeatureFilter) {
  featureConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FeatureParts
      }
    }
  }
}
    ${FeaturePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      seo_collection(variables: Seo_CollectionQueryVariables, options?: C): Promise<{data: Seo_CollectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Seo_CollectionQueryVariables, query: string}> {
        return requester<{data: Seo_CollectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Seo_CollectionQueryVariables, query: string}, Seo_CollectionQueryVariables>(Seo_CollectionDocument, variables, options);
      },
    seo_collectionConnection(variables?: Seo_CollectionConnectionQueryVariables, options?: C): Promise<{data: Seo_CollectionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Seo_CollectionConnectionQueryVariables, query: string}> {
        return requester<{data: Seo_CollectionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Seo_CollectionConnectionQueryVariables, query: string}, Seo_CollectionConnectionQueryVariables>(Seo_CollectionConnectionDocument, variables, options);
      },
    influencer(variables: InfluencerQueryVariables, options?: C): Promise<{data: InfluencerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InfluencerQueryVariables, query: string}> {
        return requester<{data: InfluencerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InfluencerQueryVariables, query: string}, InfluencerQueryVariables>(InfluencerDocument, variables, options);
      },
    influencerConnection(variables?: InfluencerConnectionQueryVariables, options?: C): Promise<{data: InfluencerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InfluencerConnectionQueryVariables, query: string}> {
        return requester<{data: InfluencerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InfluencerConnectionQueryVariables, query: string}, InfluencerConnectionQueryVariables>(InfluencerConnectionDocument, variables, options);
      },
    resource(variables: ResourceQueryVariables, options?: C): Promise<{data: ResourceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceQueryVariables, query: string}> {
        return requester<{data: ResourceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceQueryVariables, query: string}, ResourceQueryVariables>(ResourceDocument, variables, options);
      },
    resourceConnection(variables?: ResourceConnectionQueryVariables, options?: C): Promise<{data: ResourceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceConnectionQueryVariables, query: string}> {
        return requester<{data: ResourceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceConnectionQueryVariables, query: string}, ResourceConnectionQueryVariables>(ResourceConnectionDocument, variables, options);
      },
    feature(variables: FeatureQueryVariables, options?: C): Promise<{data: FeatureQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeatureQueryVariables, query: string}> {
        return requester<{data: FeatureQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeatureQueryVariables, query: string}, FeatureQueryVariables>(FeatureDocument, variables, options);
      },
    featureConnection(variables?: FeatureConnectionQueryVariables, options?: C): Promise<{data: FeatureConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeatureConnectionQueryVariables, query: string}> {
        return requester<{data: FeatureConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeatureConnectionQueryVariables, query: string}, FeatureConnectionQueryVariables>(FeatureConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  