-- Share → Decide schema lives in supabase/migrations (source of truth).
-- See: supabase/migrations/20260813140000_list_decide.sql
--
-- Clients must not SELECT/DML these tables (voter_key privacy); use RPCs only.
-- Table grants: service_role only (see docs/db/api-table-grants.sql).
-- EXECUTE:
--   create_list_decide_session → authenticated
--   get_list_decide_session, cast_list_decide_vote, lock_list_decide_session → anon + authenticated
--
-- create_list_decide_session lock_token MUST NOT call gen_random_bytes() unless
-- pgcrypto is installed on search_path. Prefer:
--   replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '')
