-- Re-seed controlled restaurant tag catalog after a data wipe.
-- Idempotent: safe to run multiple times. Does not create per-restaurant dish tags.

INSERT INTO public.tags (slug, label, category, sort_order)
VALUES
  ('pizza', 'Pizza', 'cuisine', 10),
  ('sushi', 'Sushi', 'cuisine', 20),
  ('italian', 'Italian', 'cuisine', 30),
  ('portuguese', 'Portuguese', 'cuisine', 40),
  ('coffee', 'Coffee', 'cuisine', 50),
  ('brunch', 'Brunch', 'cuisine', 60),
  ('romantic', 'Romantic', 'vibe', 10),
  ('sophisticated', 'Sophisticated', 'vibe', 20),
  ('casual', 'Casual', 'vibe', 30),
  ('michelin_star', 'Michelin star', 'award', 10),
  ('michelin_bib', 'Michelin Bib Gourmand', 'award', 20),
  ('budget', 'Budget', 'price', 10),
  ('moderate', 'Moderate', 'price', 20),
  ('upscale', 'Upscale', 'price', 30),
  ('fine_dining', 'Fine dining', 'price', 40),
  ('ramen', 'Ramen', 'cuisine', 70),
  ('burger', 'Burgers', 'cuisine', 80),
  ('bbq', 'BBQ', 'cuisine', 90),
  ('steakhouse', 'Steakhouse', 'cuisine', 100),
  ('seafood', 'Seafood', 'cuisine', 110),
  ('fried_chicken', 'Fried chicken', 'cuisine', 120),
  ('tacos', 'Tacos', 'cuisine', 130),
  ('dim_sum', 'Dim sum', 'cuisine', 140),
  ('tapas', 'Tapas', 'vibe', 250),
  ('curry', 'Curry', 'cuisine', 160),
  ('pho', 'Pho', 'cuisine', 170),
  ('dumplings', 'Dumplings', 'cuisine', 180),
  ('sandwich', 'Sandwiches', 'cuisine', 190),
  ('bakery', 'Bakery', 'cuisine', 200),
  ('ice_cream', 'Ice cream & dessert', 'cuisine', 210),
  ('japanese', 'Japanese', 'cuisine', 220),
  ('chinese', 'Chinese', 'cuisine', 230),
  ('korean', 'Korean', 'cuisine', 240),
  ('thai', 'Thai', 'cuisine', 250),
  ('vietnamese', 'Vietnamese', 'cuisine', 260),
  ('indian', 'Indian', 'cuisine', 270),
  ('mexican', 'Mexican', 'cuisine', 280),
  ('middle_eastern', 'Middle Eastern', 'cuisine', 290),
  ('greek', 'Greek', 'cuisine', 300),
  ('french', 'French', 'cuisine', 310),
  ('spanish', 'Spanish', 'cuisine', 320),
  ('american', 'American', 'cuisine', 330),
  ('brazilian', 'Brazilian', 'cuisine', 340),
  ('turkish', 'Turkish', 'cuisine', 350),
  ('lebanese', 'Lebanese', 'cuisine', 360),
  ('ethiopian', 'Ethiopian', 'cuisine', 370),
  ('peruvian', 'Peruvian', 'cuisine', 380),
  ('moroccan', 'Moroccan', 'cuisine', 390),
  ('british', 'British', 'cuisine', 400),
  ('german', 'German', 'cuisine', 410),
  ('indonesian', 'Indonesian', 'cuisine', 420),
  ('malaysian', 'Malaysian', 'cuisine', 430),
  ('filipino', 'Filipino', 'cuisine', 440),
  ('caribbean', 'Caribbean', 'cuisine', 450),
  ('african', 'African', 'cuisine', 460),
  ('date_night', 'Date night', 'vibe', 40),
  ('celebration', 'Celebration', 'vibe', 50),
  ('business', 'Business', 'vibe', 60),
  ('family_friendly', 'Family-friendly', 'vibe', 70),
  ('solo_friendly', 'Solo dining', 'vibe', 80),
  ('late_night', 'Late night', 'vibe', 90),
  ('brunch_spot', 'Brunch spot', 'vibe', 100),
  ('quick_bite', 'Quick bite', 'vibe', 110),
  ('lively', 'Lively', 'vibe', 120),
  ('quiet', 'Quiet', 'vibe', 130),
  ('cozy', 'Cozy', 'vibe', 140),
  ('rooftop', 'Rooftop', 'vibe', 150),
  ('waterfront', 'Waterfront', 'vibe', 160),
  ('outdoor_seating', 'Outdoor seating', 'vibe', 170),
  ('hidden_gem', 'Hidden gem', 'vibe', 180),
  ('chef_counter', 'Chef''s counter', 'vibe', 190),
  ('tasting_menu', 'Tasting menu', 'vibe', 200),
  ('live_music', 'Live music', 'vibe', 210),
  ('wine_bar', 'Wine bar', 'vibe', 220),
  ('craft_cocktails', 'Craft cocktails', 'vibe', 230),
  ('pet_friendly', 'Pet-friendly', 'vibe', 240),
  ('tasca', 'Tasca', 'vibe', 251),
  ('fast_casual', 'Fast casual', 'vibe', 250),
  ('food_truck', 'Food truck', 'vibe', 260),
  ('food_hall', 'Food hall', 'vibe', 270),
  ('michelin_green_star', 'Michelin Green Star', 'award', 30),
  ('michelin_1_star', 'Michelin 1 star', 'award', 40),
  ('michelin_2_star', 'Michelin 2 star', 'award', 50),
  ('michelin_3_star', 'Michelin 3 star', 'award', 60),
  ('worlds_50_best', 'World''s 50 Best', 'award', 70),
  ('repsol_sol', 'Repsol Solete', 'award', 80),
  ('james_beard', 'James Beard', 'award', 90),
  ('gault_millau', 'Gault & Millau', 'award', 100),
  ('editors_pick', 'Editor''s pick', 'award', 110),
  ('locals_favorite', 'Local favorite', 'award', 120),
  ('halal', 'Halal', 'other', 10),
  ('kosher', 'Kosher', 'other', 20),
  ('vegan_friendly', 'Vegan-friendly', 'other', 30),
  ('vegetarian_friendly', 'Vegetarian-friendly', 'other', 40),
  ('gluten_free_options', 'Gluten-free options', 'other', 50),
  ('wheelchair_accessible', 'Wheelchair accessible', 'accessibility', 10),
  ('reservations_recommended', 'Reservations recommended', 'service', 10),
  ('walk_ins_welcome', 'Walk-ins welcome', 'service', 20),
  ('step_free_entrance', 'Step-free entrance', 'accessibility', 20),
  ('accessible_restroom', 'Accessible restroom', 'accessibility', 30),
  ('accessible_seating', 'Accessible seating', 'accessibility', 40),
  ('accessible_parking_nearby', 'Accessible parking nearby', 'accessibility', 50),
  ('large_print_menu_available', 'Large-print menu available', 'accessibility', 60),
  ('takeout', 'Takeout', 'service', 30),
  ('delivery', 'Delivery', 'service', 40),
  ('counter_service', 'Counter service', 'service', 50),
  ('table_service', 'Table service', 'service', 60),
  ('private_dining', 'Private / group dining', 'service', 70),
  ('corkage_allowed', 'Corkage allowed', 'service', 80),
  ('kids_menu', 'Kids'' menu', 'service', 90)
ON CONFLICT (slug)
  DO UPDATE SET
    label = EXCLUDED.label,
    category = EXCLUDED.category,
    sort_order = EXCLUDED.sort_order;
