'use server';

/**
 * @deprecated Import from `src/libs/lists/actions` instead.
 * Thin re-export so older `src/auth/actions/list-actions` imports keep working.
 */
export {
  nameGuest,
  lockTable,
  createList,
  deleteList,
  startTable,
  fetchTable,
  addListItem,
  fetchMyLists,
  inviteToList,
  fetchListPage,
  castTableVote,
  addTablePlace,
  updateListMeta,
  fetchMyListsHub,
  resolveListSlug,
  fetchTableDecide,
  removeListMember,
  acceptListInvite,
  fetchListMetadata,
  setListMemberRole,
  declineListInvite,
  fetchListForManage,
  restaurantInMyLists,
  addRestaurantToLists,
  rejectListJoinRequest,
  approveListJoinRequest,
  fetchViewerFollowingIds,
  fetchViewerSavedListMap,
  resolveUsernameToUserId,
  removeRestaurantFromList,
  fetchOwnedListsForBilling,
  searchRestaurantsForPicker,
  fetchRestaurantListMentions,
  fetchListSummariesForViewer,
  fetchSavedRestaurantsForMap,
  fetchListMembershipForViewer,
  fetchPublicProfileByUsername,
  fetchViewerFollowingOwnersMap,
  listIdsByRestaurantIdsForUser,
  fetchFollowCircleForRestaurant,
  fetchPublicProfileActivityPage,
  fetchFollowingRestaurantsForMap,
  fetchMyOwnedListsForMapDropdown,
  fetchPublicListItemsForRestaurant,
  fetchFollowingListsForMapDropdown,
  fetchSavedRestaurantsForMapByListIds,
  fetchMyCollaboratorListsForMapDropdown,
  fetchFollowingListOwnersForRestaurants,
  fetchFollowingRestaurantsForMapByListIds,
} from 'src/libs/lists/actions';
