'use server';

/**
 * @deprecated Import from `src/libs/lists/actions` instead.
 * Thin re-export so older `src/auth/actions/list-actions` imports keep working.
 */
export {
  fetchRestaurantListMentions,
  fetchPublicListItemsForRestaurant,
  fetchViewerFollowingIds,
  fetchMyLists,
  fetchMyListsHub,
  createList,
  fetchOwnedListsForBilling,
  updateListMeta,
  deleteList,
  restaurantInMyLists,
  fetchListSummariesForViewer,
  fetchSavedRestaurantsForMap,
  fetchFollowingRestaurantsForMap,
  fetchMyOwnedListsForMapDropdown,
  fetchMyCollaboratorListsForMapDropdown,
  fetchSavedRestaurantsForMapByListIds,
  fetchFollowingRestaurantsForMapByListIds,
  fetchFollowingListsForMapDropdown,
  fetchFollowingListOwnersForRestaurants,
  fetchViewerFollowingOwnersMap,
  fetchFollowCircleForRestaurant,
  listIdsByRestaurantIdsForUser,
  fetchViewerSavedListMap,
  addRestaurantToLists,
  removeRestaurantFromList,
  addListItem,
  searchRestaurantsForPicker,
  fetchListMembershipForViewer,
  fetchListForManage,
  resolveListSlug,
  fetchListMetadata,
  fetchListPage,
  createListDecideSession,
  fetchListDecideSession,
  castListDecideVote,
  lockListDecideSession,
  createNight,
  fetchNight,
  fetchNightDecide,
  joinNight,
  castNightVote,
  fetchPublicProfileActivityPage,
  fetchPublicProfileByUsername,
  resolveUsernameToUserId,
  inviteToList,
  approveListJoinRequest,
  rejectListJoinRequest,
  setListMemberRole,
  removeListMember,
  acceptListInvite,
  declineListInvite,
} from 'src/libs/lists/actions';
